"""add_product_attributes_and_catalog_tables

Revision ID: 020158dd6d92
Revises: 7902f9d1f5bb
Create Date: 2025-10-17 19:44:55.283212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '020158dd6d92'
down_revision = '7902f9d1f5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_banners_active', table_name='banners')
    op.drop_index('idx_banners_display_order', table_name='banners')
    op.drop_index('idx_banners_type', table_name='banners')
    op.drop_index('ix_banners_banner_type', table_name='banners')
    op.drop_index('ix_banners_id', table_name='banners')
    op.drop_index('ix_banners_is_active', table_name='banners')
    op.drop_table('banners')
    op.add_column('brands', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.create_index('idx_brand_active_sort', 'brands', ['is_active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_brands_country'), 'brands', ['country'], unique=False)
    op.create_index(op.f('ix_brands_is_active'), 'brands', ['is_active'], unique=False)
    op.create_index('idx_cart_order_created', 'cart_orders', ['created_at'], unique=False)
    op.create_index('idx_cart_order_sku', 'cart_orders', ['sku_id'], unique=False)
    op.create_index('idx_cart_order_user_ordered', 'cart_orders', ['user_id', 'is_ordered'], unique=False)
    op.add_column('categories', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.create_index('idx_category_active_sort', 'categories', ['is_active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index('idx_order_stats_date', 'order_admin_stats', ['date'], unique=False)
    op.create_index('idx_order_stats_last_updated', 'order_admin_stats', ['last_updated'], unique=False)
    op.create_index('idx_order_stats_sales', 'order_admin_stats', ['today_sales_total'], unique=False)
    op.create_index('idx_order_mgmt_admin_notifications', 'order_management_admins', ['notify_on_new_orders', 'show_order_notifications'], unique=False)
    op.create_index('idx_order_mgmt_admin_permissions', 'order_management_admins', ['can_export_orders', 'can_bulk_update_orders', 'can_cancel_orders'], unique=False)
    op.add_column('product_assets', sa.Column('is_primary', sa.Boolean(), nullable=True))
    op.add_column('product_assets', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('product_assets', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('product_assets', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('product_assets', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('product_assets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('product_assets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_product_asset_primary', 'product_assets', ['is_primary'], unique=False)
    op.create_index('idx_product_asset_product_active', 'product_assets', ['product_id', 'is_active'], unique=False)
    op.create_index('idx_product_asset_type', 'product_assets', ['type'], unique=False)
    op.add_column('product_attributes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('product_attributes', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('product_attributes', sa.Column('usage_count', sa.Integer(), nullable=True))
    op.create_index('idx_product_attr_type_active', 'product_attributes', ['attribute_type', 'is_active'], unique=False)
    op.create_index('idx_product_attr_type_featured', 'product_attributes', ['attribute_type', 'is_featured'], unique=False)
    op.create_index('idx_product_attr_usage', 'product_attributes', ['usage_count'], unique=False)
    op.create_index('idx_product_discount_active', 'product_discounts', ['is_active'], unique=False)
    op.create_index('idx_product_discount_dates', 'product_discounts', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_product_discount_product_active', 'product_discounts', ['product_id', 'is_active'], unique=False)
    op.add_column('product_filters', sa.Column('usage_count', sa.Integer(), nullable=True))
    op.create_index('idx_product_filter_type_active', 'product_filters', ['filter_type', 'is_active'], unique=False)
    op.create_index('idx_product_filter_usage', 'product_filters', ['usage_count'], unique=False)
    op.add_column('product_materials', sa.Column('product_count', sa.Integer(), nullable=True))
    op.add_column('product_materials', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('product_materials', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_product_material_active', 'product_materials', ['is_active'], unique=False)
    op.create_index('idx_product_material_count', 'product_materials', ['product_count'], unique=False)
    op.create_index('idx_product_material_featured', 'product_materials', ['is_featured'], unique=False)
    op.add_column('product_searches', sa.Column('result_count', sa.Integer(), nullable=True))
    op.create_index('idx_product_search_count', 'product_searches', ['search_count'], unique=False)
    op.create_index('idx_product_search_last_searched', 'product_searches', ['last_searched'], unique=False)
    op.create_index('idx_product_search_term_count', 'product_searches', ['search_term', 'search_count'], unique=False)
    op.add_column('product_seasons', sa.Column('product_count', sa.Integer(), nullable=True))
    op.add_column('product_seasons', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('product_seasons', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_product_season_active', 'product_seasons', ['is_active'], unique=False)
    op.create_index('idx_product_season_count', 'product_seasons', ['product_count'], unique=False)
    op.create_index('idx_product_season_featured', 'product_seasons', ['is_featured'], unique=False)
    op.add_column('product_styles', sa.Column('product_count', sa.Integer(), nullable=True))
    op.add_column('product_styles', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('product_styles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_product_style_active', 'product_styles', ['is_active'], unique=False)
    op.create_index('idx_product_style_count', 'product_styles', ['product_count'], unique=False)
    op.create_index('idx_product_style_featured', 'product_styles', ['is_featured'], unique=False)
    op.alter_column('products', 'view_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('products', 'is_new',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('products', 'is_trending',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('products', 'low_stock_threshold',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.drop_index('idx_product_created_at', table_name='products')
    op.drop_index('idx_product_is_active', table_name='products')
    op.drop_index('idx_product_is_featured', table_name='products')
    op.drop_index('idx_product_rating_avg', table_name='products')
    op.drop_index('idx_product_sold_count', table_name='products')
    op.drop_index('idx_product_title', table_name='products')
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_is_featured'), 'products', ['is_featured'], unique=False)
    op.create_index(op.f('ix_products_rating_avg'), 'products', ['rating_avg'], unique=False)
    op.create_index(op.f('ix_products_sold_count'), 'products', ['sold_count'], unique=False)
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=False)
    op.add_column('reviews', sa.Column('is_verified_purchase', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('helpful_count', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('unhelpful_count', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('admin_response', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('admin_response_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_review_approved', 'reviews', ['is_approved'], unique=False)
    op.create_index('idx_review_product_rating', 'reviews', ['product_id', 'rating'], unique=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.add_column('subcategories', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.create_index('idx_subcategory_active_sort', 'subcategories', ['is_active', 'sort_order'], unique=False)
    op.create_index('idx_subcategory_category_active', 'subcategories', ['category_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_subcategories_is_active'), 'subcategories', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcategories_is_active'), table_name='subcategories')
    op.drop_index('idx_subcategory_category_active', table_name='subcategories')
    op.drop_index('idx_subcategory_active_sort', table_name='subcategories')
    op.drop_column('subcategories', 'is_featured')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index('idx_review_product_rating', table_name='reviews')
    op.drop_index('idx_review_approved', table_name='reviews')
    op.drop_column('reviews', 'updated_at')
    op.drop_column('reviews', 'admin_response_date')
    op.drop_column('reviews', 'admin_response')
    op.drop_column('reviews', 'unhelpful_count')
    op.drop_column('reviews', 'helpful_count')
    op.drop_column('reviews', 'is_featured')
    op.drop_column('reviews', 'is_approved')
    op.drop_column('reviews', 'is_verified_purchase')
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.drop_index(op.f('ix_products_sold_count'), table_name='products')
    op.drop_index(op.f('ix_products_rating_avg'), table_name='products')
    op.drop_index(op.f('ix_products_is_featured'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.create_index('idx_product_title', 'products', ['title'], unique=False)
    op.create_index('idx_product_sold_count', 'products', ['sold_count'], unique=False)
    op.create_index('idx_product_rating_avg', 'products', ['rating_avg'], unique=False)
    op.create_index('idx_product_is_featured', 'products', ['is_featured'], unique=False)
    op.create_index('idx_product_is_active', 'products', ['is_active'], unique=False)
    op.create_index('idx_product_created_at', 'products', ['created_at'], unique=False)
    op.alter_column('products', 'low_stock_threshold',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               nullable=False)
    op.alter_column('products', 'is_trending',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('products', 'is_new',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('products', 'view_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.drop_index('idx_product_style_featured', table_name='product_styles')
    op.drop_index('idx_product_style_count', table_name='product_styles')
    op.drop_index('idx_product_style_active', table_name='product_styles')
    op.drop_column('product_styles', 'updated_at')
    op.drop_column('product_styles', 'is_featured')
    op.drop_column('product_styles', 'product_count')
    op.drop_index('idx_product_season_featured', table_name='product_seasons')
    op.drop_index('idx_product_season_count', table_name='product_seasons')
    op.drop_index('idx_product_season_active', table_name='product_seasons')
    op.drop_column('product_seasons', 'updated_at')
    op.drop_column('product_seasons', 'is_featured')
    op.drop_column('product_seasons', 'product_count')
    op.drop_index('idx_product_search_term_count', table_name='product_searches')
    op.drop_index('idx_product_search_last_searched', table_name='product_searches')
    op.drop_index('idx_product_search_count', table_name='product_searches')
    op.drop_column('product_searches', 'result_count')
    op.drop_index('idx_product_material_featured', table_name='product_materials')
    op.drop_index('idx_product_material_count', table_name='product_materials')
    op.drop_index('idx_product_material_active', table_name='product_materials')
    op.drop_column('product_materials', 'updated_at')
    op.drop_column('product_materials', 'is_featured')
    op.drop_column('product_materials', 'product_count')
    op.drop_index('idx_product_filter_usage', table_name='product_filters')
    op.drop_index('idx_product_filter_type_active', table_name='product_filters')
    op.drop_column('product_filters', 'usage_count')
    op.drop_index('idx_product_discount_product_active', table_name='product_discounts')
    op.drop_index('idx_product_discount_dates', table_name='product_discounts')
    op.drop_index('idx_product_discount_active', table_name='product_discounts')
    op.drop_index('idx_product_attr_usage', table_name='product_attributes')
    op.drop_index('idx_product_attr_type_featured', table_name='product_attributes')
    op.drop_index('idx_product_attr_type_active', table_name='product_attributes')
    op.drop_column('product_attributes', 'usage_count')
    op.drop_column('product_attributes', 'is_featured')
    op.drop_column('product_attributes', 'description')
    op.drop_index('idx_product_asset_type', table_name='product_assets')
    op.drop_index('idx_product_asset_product_active', table_name='product_assets')
    op.drop_index('idx_product_asset_primary', table_name='product_assets')
    op.drop_column('product_assets', 'updated_at')
    op.drop_column('product_assets', 'created_at')
    op.drop_column('product_assets', 'file_size')
    op.drop_column('product_assets', 'height')
    op.drop_column('product_assets', 'width')
    op.drop_column('product_assets', 'is_active')
    op.drop_column('product_assets', 'is_primary')
    op.drop_index('idx_order_mgmt_admin_permissions', table_name='order_management_admins')
    op.drop_index('idx_order_mgmt_admin_notifications', table_name='order_management_admins')
    op.drop_index('idx_order_stats_sales', table_name='order_admin_stats')
    op.drop_index('idx_order_stats_last_updated', table_name='order_admin_stats')
    op.drop_index('idx_order_stats_date', table_name='order_admin_stats')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index('idx_category_active_sort', table_name='categories')
    op.drop_column('categories', 'is_featured')
    op.drop_index('idx_cart_order_user_ordered', table_name='cart_orders')
    op.drop_index('idx_cart_order_sku', table_name='cart_orders')
    op.drop_index('idx_cart_order_created', table_name='cart_orders')
    op.drop_index(op.f('ix_brands_is_active'), table_name='brands')
    op.drop_index(op.f('ix_brands_country'), table_name='brands')
    op.drop_index('idx_brand_active_sort', table_name='brands')
    op.drop_column('brands', 'is_featured')
    op.create_table('banners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('mobile_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('banner_type', postgresql.ENUM('hero', 'promo', 'category', name='bannertype'), autoincrement=False, nullable=False),
    sa.Column('cta_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cta_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='banners_pkey')
    )
    op.create_index('ix_banners_is_active', 'banners', ['is_active'], unique=False)
    op.create_index('ix_banners_id', 'banners', ['id'], unique=False)
    op.create_index('ix_banners_banner_type', 'banners', ['banner_type'], unique=False)
    op.create_index('idx_banners_type', 'banners', ['banner_type'], unique=False)
    op.create_index('idx_banners_display_order', 'banners', ['display_order'], unique=False)
    op.create_index('idx_banners_active', 'banners', ['is_active'], unique=False)
    # ### end Alembic commands ###