"""Add image_url to Category model

Revision ID: 08d25f7c076e
Revises: 22ed994e8125
Create Date: 2025-10-10 17:08:00.837514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d25f7c076e'
down_revision = '22ed994e8125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'image_url')
    # ### end Alembic commands ###