"""Add original_price to SKU

Revision ID: 0ca8b2ef41f8
Revises: 1d198e139e13
Create Date: 2025-09-24 01:28:57.764455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca8b2ef41f8'
down_revision = '1d198e139e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('original_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'original_price')
    # ### end Alembic commands ###