"""update_banner_structure

Revision ID: 1bdb7f450f83
Revises: 08d25f7c076e
Create Date: 2025-10-10 19:35:49.662888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdb7f450f83'
down_revision = '08d25f7c076e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###