"""Add cart and cart item models

Revision ID: 7371bc5cd7ba
Revises: 0ca8b2ef41f8
Create Date: 2025-09-24 01:53:36.429272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7371bc5cd7ba'
down_revision = '0ca8b2ef41f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###