"""Add wishlist models

Revision ID: 88ebdddde521
Revises: 7371bc5cd7ba
Create Date: 2025-09-24 01:58:45.856344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ebdddde521'
down_revision = '7371bc5cd7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###