"""add_payment_method_to_order

Revision ID: 8e27347fd211
Revises: b2e8ccebb8ab
Create Date: 2025-11-01 20:01:07.069657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e27347fd211'
down_revision = 'b2e8ccebb8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_banners_banner_type', table_name='banners')
    op.drop_index('ix_banners_id', table_name='banners')
    op.drop_index('ix_banners_is_active', table_name='banners')
    op.drop_table('banners')
    op.add_column('orders', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.drop_index('idx_product_market', table_name='products')
    op.drop_index('idx_product_market_active', table_name='products')
    op.drop_index('idx_product_market_active_featured', table_name='products')
    op.drop_index('idx_product_market_brand_active', table_name='products')
    op.drop_index('idx_product_market_category_active', table_name='products')
    op.drop_index('idx_product_market_subcategory_active', table_name='products')
    op.drop_column('products', 'market')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('market', postgresql.ENUM('us', 'kg', name='marketenum'), server_default=sa.text("'kg'::marketenum"), autoincrement=False, nullable=False))
    op.create_index('idx_product_market_subcategory_active', 'products', ['market', 'subcategory_id', 'is_active'], unique=False)
    op.create_index('idx_product_market_category_active', 'products', ['market', 'category_id', 'is_active'], unique=False)
    op.create_index('idx_product_market_brand_active', 'products', ['market', 'brand_id', 'is_active'], unique=False)
    op.create_index('idx_product_market_active_featured', 'products', ['market', 'is_active', 'is_featured'], unique=False)
    op.create_index('idx_product_market_active', 'products', ['market', 'is_active'], unique=False)
    op.create_index('idx_product_market', 'products', ['market'], unique=False)
    op.drop_column('orders', 'payment_method')
    op.create_table('banners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('mobile_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('banner_type', postgresql.ENUM('hero', 'promo', 'category', name='bannertype'), autoincrement=False, nullable=False),
    sa.Column('cta_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cta_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='banners_pkey')
    )
    op.create_index('ix_banners_is_active', 'banners', ['is_active'], unique=False)
    op.create_index('ix_banners_id', 'banners', ['id'], unique=False)
    op.create_index('ix_banners_banner_type', 'banners', ['banner_type'], unique=False)
    # ### end Alembic commands ###