"""add_variant_image_to_sku

Revision ID: b2e8ccebb8ab
Revises: 798a3b9aa862
Create Date: 2025-11-01 14:30:05.816908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e8ccebb8ab'
down_revision = '798a3b9aa862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('variant_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'variant_image')
    # ### end Alembic commands ###