"""update_admin_model_for_sqladmin_authentication

Revision ID: bd96af0580b1
Revises: 6994966bbf08
Create Date: 2025-10-06 16:54:06.154288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd96af0580b1'
down_revision = '6994966bbf08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_wishlists_id'), 'wishlists', ['id'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlist_items_id'), 'wishlist_items', ['id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.drop_index('ix_banners_banner_type', table_name='banners')
    op.drop_index('ix_banners_id', table_name='banners')
    op.drop_index('ix_banners_is_active', table_name='banners')
    op.drop_table('banners')
    op.add_column('admins', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('admins', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('admins', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('admins', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('admins', sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    op.alter_column('admins', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.drop_column('phone_verifications', 'market')
    op.drop_column('users', 'language')
    op.drop_column('users', 'country')
    op.drop_column('users', 'market')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('market', sa.VARCHAR(length=10), server_default=sa.text("'kg'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('country', sa.VARCHAR(length=100), server_default=sa.text("'Kyrgyzstan'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'ru'::character varying"), autoincrement=False, nullable=False))
    op.add_column('phone_verifications', sa.Column('market', sa.VARCHAR(length=10), server_default=sa.text("'kg'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.alter_column('admins', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('admins', 'is_super_admin')
    op.drop_column('admins', 'full_name')
    op.drop_column('admins', 'hashed_password')
    op.drop_column('admins', 'email')
    op.drop_column('admins', 'username')
    op.create_table('banners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('banner_type', postgresql.ENUM('SALE', 'MODEL', name='bannertype'), autoincrement=False, nullable=False),
    sa.Column('link_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='banners_pkey')
    )
    op.create_index('ix_banners_is_active', 'banners', ['is_active'], unique=False)
    op.create_index('ix_banners_id', 'banners', ['id'], unique=False)
    op.create_index('ix_banners_banner_type', 'banners', ['banner_type'], unique=False)
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_wishlist_items_id'), table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index(op.f('ix_wishlists_id'), table_name='wishlists')
    op.drop_table('wishlists')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###