"""add_market_to_user_table

Revision ID: d03b5ea9c442
Revises: 8e27347fd211
Create Date: 2025-11-02 01:25:39.813168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03b5ea9c442'
down_revision = '8e27347fd211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###