"""initial_migration

Revision ID: d0d14f41ccfd
Revises: 
Create Date: 2025-11-05 19:29:11.018682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d14f41ccfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('mobile_image_url', sa.String(length=500), nullable=True),
    sa.Column('banner_type', sa.Enum('hero', 'promo', 'category', name='bannertype'), nullable=False),
    sa.Column('cta_text', sa.String(length=100), nullable=True),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banners_banner_type'), 'banners', ['banner_type'], unique=False)
    op.create_index(op.f('ix_banners_id'), 'banners', ['id'], unique=False)
    op.create_index(op.f('ix_banners_is_active'), 'banners', ['is_active'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brand_active_sort', 'brands', ['is_active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_brands_country'), 'brands', ['country'], unique=False)
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_is_active'), 'brands', ['is_active'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_active_sort', 'categories', ['is_active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('order_admin_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('today_orders_count', sa.Integer(), nullable=True),
    sa.Column('today_orders_pending', sa.Integer(), nullable=True),
    sa.Column('today_orders_processing', sa.Integer(), nullable=True),
    sa.Column('today_orders_shipped', sa.Integer(), nullable=True),
    sa.Column('today_orders_delivered', sa.Integer(), nullable=True),
    sa.Column('today_orders_cancelled', sa.Integer(), nullable=True),
    sa.Column('today_sales_total', sa.Float(), nullable=True),
    sa.Column('today_sales_count', sa.Integer(), nullable=True),
    sa.Column('avg_order_value', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_stats_date', 'order_admin_stats', ['date'], unique=False)
    op.create_index('idx_order_stats_last_updated', 'order_admin_stats', ['last_updated'], unique=False)
    op.create_index('idx_order_stats_sales', 'order_admin_stats', ['today_sales_total'], unique=False)
    op.create_index(op.f('ix_order_admin_stats_date'), 'order_admin_stats', ['date'], unique=True)
    op.create_index(op.f('ix_order_admin_stats_id'), 'order_admin_stats', ['id'], unique=False)
    op.create_table('product_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_type', sa.String(length=50), nullable=False),
    sa.Column('filter_value', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_filter_type_active', 'product_filters', ['filter_type', 'is_active'], unique=False)
    op.create_index('idx_product_filter_usage', 'product_filters', ['usage_count'], unique=False)
    op.create_index(op.f('ix_product_filters_filter_type'), 'product_filters', ['filter_type'], unique=False)
    op.create_index(op.f('ix_product_filters_id'), 'product_filters', ['id'], unique=False)
    op.create_table('product_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('product_count', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_material_active', 'product_materials', ['is_active'], unique=False)
    op.create_index('idx_product_material_count', 'product_materials', ['product_count'], unique=False)
    op.create_index('idx_product_material_featured', 'product_materials', ['is_featured'], unique=False)
    op.create_index(op.f('ix_product_materials_id'), 'product_materials', ['id'], unique=False)
    op.create_index(op.f('ix_product_materials_name'), 'product_materials', ['name'], unique=True)
    op.create_index(op.f('ix_product_materials_slug'), 'product_materials', ['slug'], unique=True)
    op.create_table('product_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_term', sa.String(length=255), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('last_searched', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_search_count', 'product_searches', ['search_count'], unique=False)
    op.create_index('idx_product_search_last_searched', 'product_searches', ['last_searched'], unique=False)
    op.create_index('idx_product_search_term_count', 'product_searches', ['search_term', 'search_count'], unique=False)
    op.create_index(op.f('ix_product_searches_id'), 'product_searches', ['id'], unique=False)
    op.create_index(op.f('ix_product_searches_search_term'), 'product_searches', ['search_term'], unique=False)
    op.create_table('product_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('product_count', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_season_active', 'product_seasons', ['is_active'], unique=False)
    op.create_index('idx_product_season_count', 'product_seasons', ['product_count'], unique=False)
    op.create_index('idx_product_season_featured', 'product_seasons', ['is_featured'], unique=False)
    op.create_index(op.f('ix_product_seasons_id'), 'product_seasons', ['id'], unique=False)
    op.create_index(op.f('ix_product_seasons_name'), 'product_seasons', ['name'], unique=True)
    op.create_index(op.f('ix_product_seasons_slug'), 'product_seasons', ['slug'], unique=True)
    op.create_table('product_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('product_count', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_style_active', 'product_styles', ['is_active'], unique=False)
    op.create_index('idx_product_style_count', 'product_styles', ['product_count'], unique=False)
    op.create_index('idx_product_style_featured', 'product_styles', ['is_featured'], unique=False)
    op.create_index(op.f('ix_product_styles_id'), 'product_styles', ['id'], unique=False)
    op.create_index(op.f('ix_product_styles_name'), 'product_styles', ['name'], unique=True)
    op.create_index(op.f('ix_product_styles_slug'), 'product_styles', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_market'), 'users', ['market'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_role', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.String(length=500), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_user_id'), 'admins', ['user_id'], unique=True)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_table('phone_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('verification_code', sa.String(length=10), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_verifications_id'), 'phone_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_phone_verifications_phone_number'), 'phone_verifications', ['phone_number'], unique=False)
    op.create_index(op.f('ix_phone_verifications_user_id'), 'phone_verifications', ['user_id'], unique=False)
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subcategory_active_sort', 'subcategories', ['is_active', 'sort_order'], unique=False)
    op.create_index('idx_subcategory_category_active', 'subcategories', ['category_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_subcategories_category_id'), 'subcategories', ['category_id'], unique=False)
    op.create_index(op.f('ix_subcategories_id'), 'subcategories', ['id'], unique=False)
    op.create_index(op.f('ix_subcategories_is_active'), 'subcategories', ['is_active'], unique=False)
    op.create_index(op.f('ix_subcategories_name'), 'subcategories', ['name'], unique=False)
    op.create_index(op.f('ix_subcategories_slug'), 'subcategories', ['slug'], unique=False)
    op.create_table('user_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('full_address', sa.Text(), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('building', sa.String(length=50), nullable=True),
    sa.Column('apartment', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_addresses_id'), 'user_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_user_addresses_user_id'), 'user_addresses', ['user_id'], unique=False)
    op.create_table('user_payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=True),
    sa.Column('card_number_masked', sa.String(length=20), nullable=True),
    sa.Column('card_holder_name', sa.String(length=100), nullable=True),
    sa.Column('expiry_month', sa.String(length=2), nullable=True),
    sa.Column('expiry_year', sa.String(length=4), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_payment_methods_id'), 'user_payment_methods', ['id'], unique=False)
    op.create_index(op.f('ix_user_payment_methods_user_id'), 'user_payment_methods', ['user_id'], unique=False)
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_wishlists_id'), 'wishlists', ['id'], unique=False)
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_logs_admin_id'), 'admin_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_logs_id'), 'admin_logs', ['id'], unique=False)
    op.create_table('order_management_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('can_export_orders', sa.Boolean(), nullable=True),
    sa.Column('can_bulk_update_orders', sa.Boolean(), nullable=True),
    sa.Column('can_cancel_orders', sa.Boolean(), nullable=True),
    sa.Column('can_refund_orders', sa.Boolean(), nullable=True),
    sa.Column('dashboard_refresh_interval', sa.Integer(), nullable=True),
    sa.Column('show_order_notifications', sa.Boolean(), nullable=True),
    sa.Column('show_low_stock_alerts', sa.Boolean(), nullable=True),
    sa.Column('auto_confirm_orders', sa.Boolean(), nullable=True),
    sa.Column('require_manual_confirmation', sa.Boolean(), nullable=True),
    sa.Column('default_order_status', sa.String(length=20), nullable=True),
    sa.Column('notify_on_new_orders', sa.Boolean(), nullable=True),
    sa.Column('notify_on_status_changes', sa.Boolean(), nullable=True),
    sa.Column('notify_on_payment_issues', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_mgmt_admin_notifications', 'order_management_admins', ['notify_on_new_orders', 'show_order_notifications'], unique=False)
    op.create_index('idx_order_mgmt_admin_permissions', 'order_management_admins', ['can_export_orders', 'can_bulk_update_orders', 'can_cancel_orders'], unique=False)
    op.create_index(op.f('ix_order_management_admins_admin_id'), 'order_management_admins', ['admin_id'], unique=True)
    op.create_index(op.f('ix_order_management_admins_id'), 'order_management_admins', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='orderstatus'), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('delivery_address', sa.String(length=500), nullable=False),
    sa.Column('delivery_city', sa.String(length=100), nullable=True),
    sa.Column('delivery_notes', sa.String(length=500), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_admin', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('product_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_type', sa.String(length=50), nullable=False),
    sa.Column('attribute_value', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_attr_type_active', 'product_attributes', ['attribute_type', 'is_active'], unique=False)
    op.create_index('idx_product_attr_type_featured', 'product_attributes', ['attribute_type', 'is_featured'], unique=False)
    op.create_index('idx_product_attr_usage', 'product_attributes', ['usage_count'], unique=False)
    op.create_index(op.f('ix_product_attributes_attribute_type'), 'product_attributes', ['attribute_type'], unique=False)
    op.create_index(op.f('ix_product_attributes_id'), 'product_attributes', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('style_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sku_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_image', sa.String(length=500), nullable=True),
    sa.Column('additional_images', sa.JSON(), nullable=True),
    sa.Column('sold_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('is_trending', sa.Boolean(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['product_materials.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['product_seasons.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['product_styles.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_active_featured', 'products', ['is_active', 'is_featured'], unique=False)
    op.create_index('idx_product_brand_active', 'products', ['brand_id', 'is_active'], unique=False)
    op.create_index('idx_product_category_active', 'products', ['category_id', 'is_active'], unique=False)
    op.create_index('idx_product_created_desc', 'products', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_product_rating_desc', 'products', [sa.text('rating_avg DESC')], unique=False)
    op.create_index('idx_product_sold_count_desc', 'products', [sa.text('sold_count DESC')], unique=False)
    op.create_index('idx_product_subcategory_active', 'products', ['subcategory_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_is_featured'), 'products', ['is_featured'], unique=False)
    op.create_index(op.f('ix_products_material_id'), 'products', ['material_id'], unique=False)
    op.create_index(op.f('ix_products_rating_avg'), 'products', ['rating_avg'], unique=False)
    op.create_index(op.f('ix_products_season_id'), 'products', ['season_id'], unique=False)
    op.create_index(op.f('ix_products_sku_code'), 'products', ['sku_code'], unique=True)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_sold_count'), 'products', ['sold_count'], unique=False)
    op.create_index(op.f('ix_products_style_id'), 'products', ['style_id'], unique=False)
    op.create_index(op.f('ix_products_subcategory_id'), 'products', ['subcategory_id'], unique=False)
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_index(op.f('ix_interactions_product_id'), 'interactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='orderstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='orderstatus'), nullable=False),
    sa.Column('changed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_id'), 'order_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_table('product_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_asset_primary', 'product_assets', ['is_primary'], unique=False)
    op.create_index('idx_product_asset_product_active', 'product_assets', ['product_id', 'is_active'], unique=False)
    op.create_index('idx_product_asset_type', 'product_assets', ['type'], unique=False)
    op.create_index(op.f('ix_product_assets_id'), 'product_assets', ['id'], unique=False)
    op.create_index(op.f('ix_product_assets_product_id'), 'product_assets', ['product_id'], unique=False)
    op.create_table('product_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_discount_active', 'product_discounts', ['is_active'], unique=False)
    op.create_index('idx_product_discount_dates', 'product_discounts', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_product_discount_product_active', 'product_discounts', ['product_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_product_discounts_id'), 'product_discounts', ['id'], unique=False)
    op.create_index(op.f('ix_product_discounts_product_id'), 'product_discounts', ['product_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('unhelpful_count', sa.Integer(), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('admin_response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_approved', 'reviews', ['is_approved'], unique=False)
    op.create_index('idx_review_product_rating', 'reviews', ['product_id', 'rating'], unique=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku_code', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('variant_image', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_id'), 'skus', ['id'], unique=False)
    op.create_index(op.f('ix_skus_product_id'), 'skus', ['product_id'], unique=False)
    op.create_index(op.f('ix_skus_sku_code'), 'skus', ['sku_code'], unique=True)
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_id'), 'user_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_user_notifications_notification_type'), 'user_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_user_notifications_order_id'), 'user_notifications', ['order_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlist_items_id'), 'wishlist_items', ['id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_table('cart_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_ordered', sa.Boolean(), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cart_order_created', 'cart_orders', ['created_at'], unique=False)
    op.create_index('idx_cart_order_sku', 'cart_orders', ['sku_id'], unique=False)
    op.create_index('idx_cart_order_user_ordered', 'cart_orders', ['user_id', 'is_ordered'], unique=False)
    op.create_index(op.f('ix_cart_orders_id'), 'cart_orders', ['id'], unique=False)
    op.create_index(op.f('ix_cart_orders_sku_id'), 'cart_orders', ['sku_id'], unique=False)
    op.create_index(op.f('ix_cart_orders_user_id'), 'cart_orders', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('sku_code', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_sku_id'), 'order_items', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_sku_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_cart_orders_user_id'), table_name='cart_orders')
    op.drop_index(op.f('ix_cart_orders_sku_id'), table_name='cart_orders')
    op.drop_index(op.f('ix_cart_orders_id'), table_name='cart_orders')
    op.drop_index('idx_cart_order_user_ordered', table_name='cart_orders')
    op.drop_index('idx_cart_order_sku', table_name='cart_orders')
    op.drop_index('idx_cart_order_created', table_name='cart_orders')
    op.drop_table('cart_orders')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_wishlist_items_id'), table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_order_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_notification_type'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_skus_sku_code'), table_name='skus')
    op.drop_index(op.f('ix_skus_product_id'), table_name='skus')
    op.drop_index(op.f('ix_skus_id'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index('idx_review_product_rating', table_name='reviews')
    op.drop_index('idx_review_approved', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_product_discounts_product_id'), table_name='product_discounts')
    op.drop_index(op.f('ix_product_discounts_id'), table_name='product_discounts')
    op.drop_index('idx_product_discount_product_active', table_name='product_discounts')
    op.drop_index('idx_product_discount_dates', table_name='product_discounts')
    op.drop_index('idx_product_discount_active', table_name='product_discounts')
    op.drop_table('product_discounts')
    op.drop_index(op.f('ix_product_assets_product_id'), table_name='product_assets')
    op.drop_index(op.f('ix_product_assets_id'), table_name='product_assets')
    op.drop_index('idx_product_asset_type', table_name='product_assets')
    op.drop_index('idx_product_asset_product_active', table_name='product_assets')
    op.drop_index('idx_product_asset_primary', table_name='product_assets')
    op.drop_table('product_assets')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_product_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.drop_index(op.f('ix_products_subcategory_id'), table_name='products')
    op.drop_index(op.f('ix_products_style_id'), table_name='products')
    op.drop_index(op.f('ix_products_sold_count'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_sku_code'), table_name='products')
    op.drop_index(op.f('ix_products_season_id'), table_name='products')
    op.drop_index(op.f('ix_products_rating_avg'), table_name='products')
    op.drop_index(op.f('ix_products_material_id'), table_name='products')
    op.drop_index(op.f('ix_products_is_featured'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_index('idx_product_subcategory_active', table_name='products')
    op.drop_index('idx_product_sold_count_desc', table_name='products')
    op.drop_index('idx_product_rating_desc', table_name='products')
    op.drop_index('idx_product_created_desc', table_name='products')
    op.drop_index('idx_product_category_active', table_name='products')
    op.drop_index('idx_product_brand_active', table_name='products')
    op.drop_index('idx_product_active_featured', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_product_attributes_id'), table_name='product_attributes')
    op.drop_index(op.f('ix_product_attributes_attribute_type'), table_name='product_attributes')
    op.drop_index('idx_product_attr_usage', table_name='product_attributes')
    op.drop_index('idx_product_attr_type_featured', table_name='product_attributes')
    op.drop_index('idx_product_attr_type_active', table_name='product_attributes')
    op.drop_table('product_attributes')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_management_admins_id'), table_name='order_management_admins')
    op.drop_index(op.f('ix_order_management_admins_admin_id'), table_name='order_management_admins')
    op.drop_index('idx_order_mgmt_admin_permissions', table_name='order_management_admins')
    op.drop_index('idx_order_mgmt_admin_notifications', table_name='order_management_admins')
    op.drop_table('order_management_admins')
    op.drop_index(op.f('ix_admin_logs_id'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_admin_id'), table_name='admin_logs')
    op.drop_table('admin_logs')
    op.drop_index(op.f('ix_wishlists_id'), table_name='wishlists')
    op.drop_table('wishlists')
    op.drop_index(op.f('ix_user_payment_methods_user_id'), table_name='user_payment_methods')
    op.drop_index(op.f('ix_user_payment_methods_id'), table_name='user_payment_methods')
    op.drop_table('user_payment_methods')
    op.drop_index(op.f('ix_user_addresses_user_id'), table_name='user_addresses')
    op.drop_index(op.f('ix_user_addresses_id'), table_name='user_addresses')
    op.drop_table('user_addresses')
    op.drop_index(op.f('ix_subcategories_slug'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_name'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_is_active'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_id'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_category_id'), table_name='subcategories')
    op.drop_index('idx_subcategory_category_active', table_name='subcategories')
    op.drop_index('idx_subcategory_active_sort', table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_index(op.f('ix_phone_verifications_user_id'), table_name='phone_verifications')
    op.drop_index(op.f('ix_phone_verifications_phone_number'), table_name='phone_verifications')
    op.drop_index(op.f('ix_phone_verifications_id'), table_name='phone_verifications')
    op.drop_table('phone_verifications')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_user_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_market'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_product_styles_slug'), table_name='product_styles')
    op.drop_index(op.f('ix_product_styles_name'), table_name='product_styles')
    op.drop_index(op.f('ix_product_styles_id'), table_name='product_styles')
    op.drop_index('idx_product_style_featured', table_name='product_styles')
    op.drop_index('idx_product_style_count', table_name='product_styles')
    op.drop_index('idx_product_style_active', table_name='product_styles')
    op.drop_table('product_styles')
    op.drop_index(op.f('ix_product_seasons_slug'), table_name='product_seasons')
    op.drop_index(op.f('ix_product_seasons_name'), table_name='product_seasons')
    op.drop_index(op.f('ix_product_seasons_id'), table_name='product_seasons')
    op.drop_index('idx_product_season_featured', table_name='product_seasons')
    op.drop_index('idx_product_season_count', table_name='product_seasons')
    op.drop_index('idx_product_season_active', table_name='product_seasons')
    op.drop_table('product_seasons')
    op.drop_index(op.f('ix_product_searches_search_term'), table_name='product_searches')
    op.drop_index(op.f('ix_product_searches_id'), table_name='product_searches')
    op.drop_index('idx_product_search_term_count', table_name='product_searches')
    op.drop_index('idx_product_search_last_searched', table_name='product_searches')
    op.drop_index('idx_product_search_count', table_name='product_searches')
    op.drop_table('product_searches')
    op.drop_index(op.f('ix_product_materials_slug'), table_name='product_materials')
    op.drop_index(op.f('ix_product_materials_name'), table_name='product_materials')
    op.drop_index(op.f('ix_product_materials_id'), table_name='product_materials')
    op.drop_index('idx_product_material_featured', table_name='product_materials')
    op.drop_index('idx_product_material_count', table_name='product_materials')
    op.drop_index('idx_product_material_active', table_name='product_materials')
    op.drop_table('product_materials')
    op.drop_index(op.f('ix_product_filters_id'), table_name='product_filters')
    op.drop_index(op.f('ix_product_filters_filter_type'), table_name='product_filters')
    op.drop_index('idx_product_filter_usage', table_name='product_filters')
    op.drop_index('idx_product_filter_type_active', table_name='product_filters')
    op.drop_table('product_filters')
    op.drop_index(op.f('ix_order_admin_stats_id'), table_name='order_admin_stats')
    op.drop_index(op.f('ix_order_admin_stats_date'), table_name='order_admin_stats')
    op.drop_index('idx_order_stats_sales', table_name='order_admin_stats')
    op.drop_index('idx_order_stats_last_updated', table_name='order_admin_stats')
    op.drop_index('idx_order_stats_date', table_name='order_admin_stats')
    op.drop_table('order_admin_stats')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index('idx_category_active_sort', table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_is_active'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_country'), table_name='brands')
    op.drop_index('idx_brand_active_sort', table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_banners_is_active'), table_name='banners')
    op.drop_index(op.f('ix_banners_id'), table_name='banners')
    op.drop_index(op.f('ix_banners_banner_type'), table_name='banners')
    op.drop_table('banners')
    # ### end Alembic commands ###