"""add_market_to_admin_table

Revision ID: e5673d0dce90
Revises: d03b5ea9c442
Create Date: 2025-11-02 14:31:49.159924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5673d0dce90'
down_revision = 'd03b5ea9c442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('market', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'market')
    # ### end Alembic commands ###